### ISSUE TITLE
Fix: execution time Flood Mem Leak all this

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-param#3]
The Following happens and is reproduce able by Change same route.attr every secund
```
done-serve starting on http://localhost:8080
Received client connection
Live-reload server listening on port 8012
file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:5
function buildParam(prefix, obj, add) {
                   ^

RangeError: Maximum call stack size exceeded
    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:5:20)
    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:12:4)
    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:12:4)

    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:12:4)
    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:12:4)
    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:12:4)
    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:12:4)
    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:12:4)
    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:12:4)
    at buildParam (file:/home/frank/workspace/peep/frontend-showroom/node_modules/can-param/can-param.js:12:4)
```

**Comment by justinbmeyer** [comment]
Can you provide more information? I am not sure what is being reported or how to fix it. 

Do you have a cycle in your routing data? Can you create a small test?
